Adicionando projeto final - M de Maravilhosa
reprograma/On5-projeto-final pull request #18
Opened 2020-07-24 20:56 UTC by jaquelindacostabotelho

Por favor verifica meu código,

Obrigada! Jaqueline

2020-07-25 01:17 UTC, JulianaAmoasei requested changes
@jaquelindacostabotelho a imagem da sua homenageada na página principal não está sendo carregada. Por favor revise o link e lembre-se que JS, CSS e HTML fazem diferenciação entre maiúsculas e minúsculas.

2020-07-25 10:27 UTC, jaquelindacostabotelho commented
Bom dia Ju @JulianaAmoasei 
O caminho está ok e para mim aparece correta a imagem da minha maravilhosa na página principal. Não entendo o que preciso alterar, poderia me ajudar nisso por favor? Obrigada e desculpa o transtorno!

Está dessa forma no meu css:
.header
url(../img/foto-mae.JPG);

2020-07-25 10:33 UTC, jaquelindacostabotelho commented
Ju, vi aqui, de fato o estava jpg no tipo da foto, alterei para JPG, que é como de fato está a foto.

Obrigada viu! @JulianaAmoasei

2020-07-29 17:57 UTC, JulianaAmoasei approved these changes

2020-07-29 17:59 UTC, merged