Adicionando pagina m de maravilhosa
reprograma/On5-projeto-final pull request #26
Opened 2020-07-25 01:09 UTC by thaismuller

ceci, qualquer coisa chama!!!

2020-07-25 02:03 UTC, JulianaAmoasei requested changes
@thaismuller você esqueceu de alterar o arquivo principal `index.html` com os caminhos e infos da sua página. Por favor siga as instruções do `readme.md` e revise :)

2020-07-25 02:34 UTC, thaismuller commented
oi ju, boa noite. Eu alterei o index e na hora do git eu dei git add . , na teoria deveria adicionar todos os elementos que mudei. Consegue me ajudar?

2020-07-25 02:37 UTC, thaismuller commented
esqueci de dar git add index.html mesmo, aí não vai. Obrigada pelo feedback <3 
boa noite!

2020-07-29 18:19 UTC, JulianaAmoasei approved these changes

2020-07-29 18:20 UTC, merged