Valeria nascimento
reprograma/On5-projeto-final pull request #42
Opened 2020-07-30 00:40 UTC by valeriandj

2020-08-04 01:23 UTC, JulianaAmoasei commented on index.html
>            <a href="#">
substituir a # pelo endereço da sua página conforme está nas instruções do `readme.md`

2020-08-04 01:24 UTC, JulianaAmoasei commented on index.html
> +            <img class="img-responsive" src="./img/neusa sousa.jpg" alt="" />
A imagem da sua homenageada deve estar dentro da pasta do seu projeto. Veja no `readme.md` o modelo.

2020-08-04 01:27 UTC, JulianaAmoasei requested changes
@valeriandj você precisa fazer algumas correções antes que eu possa fazer o merge.
- adicionar o caminho para a sua página pessoal no HTML principal `index.html`
- a imagem da sua homenageada deve estar dentro da pasta do seu projeto.
- A pasta do seu projeto deve estar organizada, somente com um html, pasta img, pasta css e pasta js.
Por favor dê uma olhada nas instruções que deixamos no arquivo `readme.md`, lá tem o modelinho de como tem que preencher no `index.html` e a estrutura que tem que estar a sua pasta. :rocket:

2020-08-05 12:32 UTC, valeriandj commented on index.html
>            <a href="#">
Juliana já foi corrigido, não entendi porque não subiu.
  <div class="maravilhosas__perfil">
          <a href="./maravilhosas/valerianascimento/vnindex.html">
            <img class="img-responsive" src="./img/neusa sousa.jpg" alt="" />
            <p>Neusa Santos Sousa</p>
          </a>
        </div>

2020-08-05 12:32 UTC, valeriandj commented on index.html
> +            <img class="img-responsive" src="./img/neusa sousa.jpg" alt="" />
A imagem já esta inserida em todas as páginas.

2020-08-05 14:04 UTC, valeriandj commented
Modificacoes finais incluídas

2020-08-10 19:40 UTC, JulianaAmoasei approved these changes

2020-08-10 19:41 UTC, merged